# -*- coding: utf-8 -*-
"""notebook3060e75695

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/arghadipdutta/notebook3060e75695.a14d917c-b4df-4333-a1d6-79cc1ec6d312.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260501/auto/storage/goog4_request%26X-Goog-Date%3D20260501T102937Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D516cd3773e421cd3ef56545d4961fcac7ecd6e0bd6223aa69cab0fa83433191078b5ce8e95a6b8cd9b20bbdc327d003ec8f7d6fdabb4c41fc605470cc4d4be9c0a3f93d62be4b86e75f80ad30dc374978e936c7198e3269c9e682db9dd1c4c279ec742d235f1e7b15524ba48871031dc159cc5c2a420fd65ec808fc261678071b1af1364a5af79b464a7f1057c0037d0784f3eea2774dddc46445d9d93a00019878022195a870cf8155fc2bf5cccfc6c611eae33148d535d91a2c87b017fbaca9ad789b587ad3c98f0e7879a66e60ba9912ada1d681b9af93a421705b59681ed00ddb93f47370048c16a35ea4d4c2d662b7d9a48906164d6f95e297e589dd25b
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

gourangamaitymca_kmc_renal_liver_dataset_classification_path = kagglehub.dataset_download('gourangamaitymca/kmc-renal-liver-dataset-classification')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import torch
from torchinfo import summary
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import _LRScheduler
import torch.utils.data as data
import torchvision.models as models
import torchvision.transforms as transforms
import torchvision.datasets as datasets
from torch.optim.lr_scheduler import ReduceLROnPlateau
from sklearn import decomposition
from sklearn import manifold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc, roc_auc_score
from tqdm.notebook import tqdm, trange
import matplotlib.pyplot as plt
import numpy as np
import copy
import random
import time
from torch.utils.data import Dataset, DataLoader, random_split
import os
import seaborn as sns

import kagglehub

# Download latest version
path = kagglehub.dataset_download("gourangamaitymca/kmc-renal-liver-dataset-classification")

print("Path to dataset files:", path)

BATCH_SIZE=16
IMG_SIZE=224

train_transform=transforms.Compose([
    transforms.Resize((IMG_SIZE,IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.RandomVerticalFlip(),
    transforms.ToTensor(),

    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225]
    )
])

val_test_transform=transforms.Compose([
    transforms.Resize((IMG_SIZE,IMG_SIZE)),
    transforms.ToTensor(),

    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225]
    )
])

train_dataset=datasets.ImageFolder(
    root="/kaggle/input/datasets/gourangamaitymca/kmc-renal-liver-dataset-classification/TCGA-KIDNEY-FINAL/Data/Training",
    transform=train_transform
)

val_dataset=datasets.ImageFolder(
    root="/kaggle/input/datasets/gourangamaitymca/kmc-renal-liver-dataset-classification/TCGA-KIDNEY-FINAL/Data/Validation",
    transform=val_test_transform
)
test_dataset=datasets.ImageFolder(
    root="/kaggle/input/datasets/gourangamaitymca/kmc-renal-liver-dataset-classification/TCGA-KIDNEY-FINAL/Data/Test",
    transform=val_test_transform
)

from torch.utils.data import DataLoader

train_loader=DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4
)
val_loader=DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4
)
test_loader=DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4
)

import torch
import torch.nn as nn

# ----------------------------
# DropPath
# ----------------------------
class DropPath(nn.Module):
    def __init__(self, drop_prob=0.):
        super().__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        if self.drop_prob == 0. or not self.training:
            return x
        keep_prob = 1 - self.drop_prob
        shape = (x.shape[0],) + (1,) * (x.ndim - 1)
        random_tensor = keep_prob + torch.rand(shape, device=x.device)
        random_tensor.floor_()
        return x.div(keep_prob) * random_tensor


# ----------------------------
# MLP
# ----------------------------
class MLP(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.fc1 = nn.Linear(dim, dim * 4)
        self.act = nn.GELU()
        self.fc2 = nn.Linear(dim * 4, dim)

    def forward(self, x):
        return self.fc2(self.act(self.fc1(x)))


# ----------------------------
# Window Partition / Reverse
# ----------------------------
def window_partition(x, window_size):
    B, H, W, C = x.shape
    x = x.view(B, H//window_size, window_size, W//window_size, window_size, C)
    return x.permute(0,1,3,2,4,5).contiguous().view(-1, window_size, window_size, C)

def window_reverse(windows, window_size, H, W):
    B = int(windows.shape[0] / (H * W / window_size / window_size))
    x = windows.view(B, H//window_size, W//window_size, window_size, window_size, -1)
    x = x.permute(0,1,3,2,4,5).contiguous()
    return x.view(B, H, W, -1)


# ----------------------------
# Window Attention
# ----------------------------
class WindowAttention(nn.Module):
    def __init__(self, dim, num_heads):
        super().__init__()
        self.num_heads = num_heads
        self.scale = (dim // num_heads) ** -0.5

        self.qkv = nn.Linear(dim, dim * 3)
        self.proj = nn.Linear(dim, dim)

    def forward(self, x, mask=None):
        B_, N, C = x.shape

        qkv = self.qkv(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads)
        qkv = qkv.permute(2, 0, 3, 1, 4)

        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) * self.scale

        if mask is not None:
          nW = mask.shape[0]

        # 🔥 CRITICAL FIX
          attn = attn.view(B_ // nW, nW, self.num_heads, N, N)
          attn = attn + mask.unsqueeze(1).unsqueeze(0)
          attn = attn.view(-1, self.num_heads, N, N)

        attn = attn.softmax(dim=-1)

        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
        return self.proj(x)



    # def forward(self, x, mask=None):
    #     B_, N, C = x.shape

    #     qkv = self.qkv(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads)
    #     qkv = qkv.permute(2, 0, 3, 1, 4)

    #     q, k, v = qkv[0], qkv[1], qkv[2]

    #     attn = (q @ k.transpose(-2, -1)) * self.scale

    #     if mask is not None:
    #         attn = attn + mask.unsqueeze(1)

    #     attn = attn.softmax(dim=-1)

    #     x = (attn @ v).transpose(1,2).reshape(B_, N, C)
    #     return self.proj(x)


# ----------------------------
# Swin Block
# ----------------------------
class SwinBlock(nn.Module):
    def __init__(self, dim, num_heads, window_size, shift_size):
        super().__init__()

        self.window_size = window_size
        self.shift_size = shift_size

        self.norm1 = nn.LayerNorm(dim)
        self.attn = WindowAttention(dim, num_heads)

        self.norm2 = nn.LayerNorm(dim)
        self.mlp = MLP(dim)

    def create_mask(self, H, W, device):
        if self.shift_size == 0:
            return None

        img_mask = torch.zeros((1, H, W, 1), device=device)

        cnt = 0
        for h in (slice(0, -self.window_size),
                  slice(-self.window_size, -self.shift_size),
                  slice(-self.shift_size, None)):
            for w in (slice(0, -self.window_size),
                      slice(-self.window_size, -self.shift_size),
                      slice(-self.shift_size, None)):
                img_mask[:, h, w, :] = cnt
                cnt += 1

        mask_windows = window_partition(img_mask, self.window_size)
        mask_windows = mask_windows.view(-1, self.window_size * self.window_size)

        attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
        attn_mask = attn_mask.masked_fill(attn_mask != 0, float('-inf')).masked_fill(attn_mask == 0, 0)

        return attn_mask

    def forward(self, x, H, W):
        B, L, C = x.shape
        shortcut = x

        x = self.norm1(x)
        x = x.view(B, H, W, C)

        # Shift
        if self.shift_size > 0:
            x = torch.roll(x, shifts=(-self.shift_size, -self.shift_size), dims=(1,2))

        # Partition
        x_windows = window_partition(x, self.window_size)
        x_windows = x_windows.view(-1, self.window_size * self.window_size, C)

        mask = self.create_mask(H, W, x.device)
        x_windows = self.attn(x_windows, mask)

        # Reverse
        x = window_reverse(x_windows.view(-1, self.window_size, self.window_size, C),
                           self.window_size, H, W)

        if self.shift_size > 0:
            x = torch.roll(x, shifts=(self.shift_size, self.shift_size), dims=(1,2))

        x = x.view(B, H*W, C)

        x = shortcut + x
        x = x + self.mlp(self.norm2(x))

        return x


# ----------------------------
# Patch Merging
# ----------------------------
class PatchMerging(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.reduction = nn.Linear(4 * dim, 2 * dim)

    def forward(self, x, H, W):
        B, L, C = x.shape
        x = x.view(B, H, W, C)

        x0 = x[:, 0::2, 0::2, :]
        x1 = x[:, 1::2, 0::2, :]
        x2 = x[:, 0::2, 1::2, :]
        x3 = x[:, 1::2, 1::2, :]

        x = torch.cat([x0, x1, x2, x3], -1)
        x = x.view(B, -1, 4 * C)

        return self.reduction(x)


# ----------------------------
# Patch Embedding
# ----------------------------
class PatchEmbed(nn.Module):
    def __init__(self):
        super().__init__()
        self.proj = nn.Conv2d(3, 96, kernel_size=4, stride=4)

    def forward(self, x):
        x = self.proj(x)
        B, C, H, W = x.shape
        return x.flatten(2).transpose(1,2), H, W


# ----------------------------
# Swin Transformer (FULL)
# ----------------------------
class SwinTransformer(nn.Module):
    def __init__(self, num_classes=4):
        super().__init__()

        self.patch_embed = PatchEmbed()

        # Stage 1 (96 dim, depth 2)
        self.stage1 = nn.ModuleList([
            SwinBlock(96, 3, 7, 0),
            SwinBlock(96, 3, 7, 3)
        ])

        self.merge1 = PatchMerging(96)

        # Stage 2 (192 dim, depth 2)
        self.stage2 = nn.ModuleList([
            SwinBlock(192, 6, 7, 0),
            SwinBlock(192, 6, 7, 3)
        ])

        self.merge2 = PatchMerging(192)

        # Stage 3 (384 dim, depth 6)
        self.stage3 = nn.ModuleList([
            SwinBlock(384, 12, 7, 0 if i % 2 == 0 else 3)
            for i in range(6)
        ])

        self.merge3 = PatchMerging(384)

        # Stage 4 (768 dim, depth 2)
        self.stage4 = nn.ModuleList([
            SwinBlock(768, 24, 7, 0),
            SwinBlock(768, 24, 7, 3)
        ])

        self.norm = nn.LayerNorm(768)
        self.head = nn.Linear(768, num_classes)

    def forward(self, x):
        x, H, W = self.patch_embed(x)

        for blk in self.stage1:
            x = blk(x, H, W)

        x = self.merge1(x, H, W)
        H, W = H//2, W//2

        for blk in self.stage2:
            x = blk(x, H, W)

        x = self.merge2(x, H, W)
        H, W = H//2, W//2

        for blk in self.stage3:
            x = blk(x, H, W)

        x = self.merge3(x, H, W)
        H, W = H//2, W//2

        for blk in self.stage4:
            x = blk(x, H, W)

        x = self.norm(x)
        x = x.mean(dim=1)

        return self.head(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Targets=np.array(train_dataset.targets)
indices=np.arange(len(Targets))

from sklearn.utils.class_weight import compute_class_weight
classes=np.unique(Targets)
weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=Targets
)

class_weights = torch.tensor(weights, dtype=torch.float).cuda()

num_classes=len(np.unique(Targets))

model=SwinTransformer(num_classes=4)

from torchinfo import summary

summary(model, input_size=(16 ,3, 224, 224))

optimizer = optim.Adam(model.parameters(), lr= 0.0001, weight_decay=1e-5)
scheduler = ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.1,
    patience=3
)

weights_tensor = torch.tensor(weights, dtype=torch.float).to(device)
criterion=nn.CrossEntropyLoss(weight=weights_tensor)
class_names=['class1','class2','class3','class4']

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from tqdm import tqdm
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score, roc_curve, auc
from sklearn.preprocessing import label_binarize


# -------------------- Metric Computation --------------------
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def compute_metrics(labels, preds):
    acc = accuracy_score(labels, preds)
    prec = precision_score(labels, preds, average='weighted', zero_division=0)
    rec = recall_score(labels, preds, average='weighted', zero_division=0)
    f1 = f1_score(labels, preds, average='weighted', zero_division=0)
     # Sensitivity & Specificity (macro-averaged)
    cm = confusion_matrix(labels, preds)
    sensitivity_per_class = []
    specificity_per_class = []
    for i in range(cm.shape[0]):
        TP = cm[i, i]
        FN = np.sum(cm[i, :]) - TP
        FP = np.sum(cm[:, i]) - TP
        TN = np.sum(cm) - (TP + FP + FN)

        sensitivity = TP / (TP + FN) if (TP + FN) > 0 else 0.0
        specificity = TN / (TN + FP) if (TN + FP) > 0 else 0.0
        sensitivity_per_class.append(sensitivity)
        specificity_per_class.append(specificity)

    sensitivity_macro = np.mean(sensitivity_per_class)
    specificity_macro = np.mean(specificity_per_class)

    return acc, prec, rec, f1,sensitivity_macro, specificity_macro

# -------------------- Normalize Function --------------------
def normalize_image(img_tensor):
    img = img_tensor.clone()
    img = (img - img.min()) / (img.max() - img.min() + 1e-8)
    return img

# -------------------- Training Step --------------------
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    all_preds, all_labels = [], []
    running_loss = 0.0

    for images, labels in tqdm(loader, desc="Training", leave=False):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * images.size(0)
        preds = torch.argmax(outputs, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    acc, prec, rec, f1,sensitivity_macro, specificity_macro = compute_metrics(all_labels, all_preds)
    return epoch_loss, acc, prec, rec, f1,sensitivity_macro, specificity_macro

# -------------------- Validation Step --------------------
def validate_one_epoch(model, loader, criterion, device):
    model.eval()
    all_preds, all_labels = [], []
    running_loss = 0.0

    with torch.no_grad():
        for images, labels in tqdm(loader, desc="Validation", leave=False):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            preds = torch.argmax(outputs, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    acc, prec, rec, f1,sensitivity_macro, specificity_macro = compute_metrics(all_labels, all_preds)
    return epoch_loss, acc, prec, rec, f1,sensitivity_macro, specificity_macro

def test_model(model, loader, criterion, device, class_names=None):
    model.eval()
    all_preds, all_labels = [], []
    all_images, all_probs = [], []
    running_loss = 0.0

    with torch.no_grad():
        for images, labels in tqdm(loader, desc="Testing", leave=False):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            probs = torch.softmax(outputs, dim=1)
            preds = torch.argmax(probs, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_images.extend(images.cpu())
            all_probs.extend(probs.cpu().numpy())

    avg_loss = running_loss / len(loader.dataset)
    acc, prec, rec, f1,sensitivity_macro, specificity_macro = compute_metrics(all_labels, all_preds)

    cm = confusion_matrix(all_labels, all_preds)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(cmap=plt.cm.Blues, xticks_rotation=45)
    plt.title("Confusion Matrix")
    plt.tight_layout()
    plt.show()

    print("\n🔍 Classification Report")
    print(classification_report(all_labels, all_preds, target_names=class_names, zero_division=0))

    return avg_loss, acc, prec, rec, f1, all_labels, all_preds, all_images, torch.tensor(np.vstack(all_probs))




# -------------------- Plot Incorrect Predictions --------------------
def plot_most_incorrect(incorrect, classes, n_images, normalize=True):
    rows = int(np.sqrt(n_images))
    cols = int(np.sqrt(n_images))

    fig = plt.figure(figsize=(25, 20))
    for i in range(min(rows * cols, len(incorrect))):
        ax = fig.add_subplot(rows, cols, i+1)
        image, true_label, probs = incorrect[i]
        image = image.permute(1, 2, 0)
        true_prob = probs[true_label]
        incorrect_prob, incorrect_label = torch.max(probs, dim=0)
        true_class = classes[true_label]
        incorrect_class = classes[incorrect_label]

        if normalize:
            image = normalize_image(image)

        ax.imshow(image.numpy())
        ax.set_title(f'True: {true_class} ({true_prob:.3f})\nPred: {incorrect_class} ({incorrect_prob:.3f})')
        ax.axis('off')

    fig.subplots_adjust(hspace=0.4)
    plt.show()

def run_training(model, train_loader, val_loader, test_loader, optimizer, criterion, device, class_names=None, num_epochs=400,patience=20 ):
    best_val_loss = float('inf')

    # Lists to store loss and accuracy for each epoch
    train_losses, val_losses = [], []
    train_accuracies, val_accuracies = [],[]
    epochs_without_improvement = 0

    for epoch in range(num_epochs):
        train_loss, train_acc, train_prec, train_rec, train_f1,train_sensitivity_macro, train_specificity_macro = train_one_epoch(model, train_loader, optimizer, criterion, device)
        val_loss, val_acc, val_prec, val_rec, val_f1,val_sensitivity_macro, val_specificity_macro = validate_one_epoch(model, val_loader, criterion, device)
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accuracies.append(train_acc)
        val_accuracies.append(val_acc)
        # 🔹 Print current learning rate(s)
        current_lrs = [param_group['lr'] for param_group in optimizer.param_groups]
        print(f"\nEpoch [{epoch+1}/{num_epochs}] - Current LRs: {current_lrs}")

        print(f"\nEpoch [{epoch+1}/{num_epochs}]")
        print(f"Train - Loss: {train_loss:.4f}, Acc: {train_acc:.4f}, Prec: {train_prec:.4f}, Recall: {train_rec:.4f}, F1: {train_f1:.4f}, specificity: {train_specificity_macro:.4f},sensitivity: {train_sensitivity_macro:.4f}")
        print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_acc:.4f}, Prec: {val_prec:.4f}, Recall: {val_rec:.4f}, F1: {val_f1:.4f},specificity: {val_specificity_macro:.4f},sensitivity: {val_sensitivity_macro:.4f}")
        scheduler.step(val_loss)
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_without_improvement = 0
            torch.save(model.state_dict(), 'best_model.pth')
            print(f"✅ Saved best model (val_loss: {val_loss:.4f})")
        else:
            epochs_without_improvement += 1
            print(f"⏳ No improvement in val_loss for {epochs_without_improvement} epoch(s)")

            if epochs_without_improvement >= patience:
                print(f"🛑 Early stopping triggered after {patience} epochs without improvement.")
                break


    # 📊 Plotting Loss and Accuracy Curves
    plt.figure(figsize=(12, 5))

    # Loss Curve
    plt.subplot(1, 2, 1)
    plt.plot(train_losses, label='Train Loss', marker='o')
    plt.plot(val_losses, label='Validation Loss', marker='o')
    plt.title("Loss over Epochs")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(train_accuracies, label='Train Accuracy', marker='o')
    plt.plot(val_accuracies, label='Validation Accuracy', marker='o')
    plt.title("Accuracy over Epochs")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.grid(True)
    plt.legend()

    plt.tight_layout()
    plt.show()

    # Load the best model before testing
    model.load_state_dict(torch.load('best_model.pth'))
    print("📥 Loaded the best saved model for final testing.")

    print("\n🔍 Evaluating on Test Set:")
    test_loss, test_acc, test_prec, test_rec, test_f1, all_labels, all_preds, all_images, all_probs = test_model(
        model, test_loader, criterion, device, class_names
    )

    print(f"Test - Loss: {test_loss:.4f}, Acc: {test_acc:.4f}, Prec: {test_prec:.4f}, Recall: {test_rec:.4f}, F1: {test_f1:.4f}")

    corrects = torch.eq(torch.tensor(all_labels), torch.tensor(all_preds))
    num_correct = corrects.sum().item()
    total = len(corrects)
    print(f"✅ Correct Predictions: {num_correct}/{total} ({100 * num_correct / total:.2f}%)")

    incorrect_examples = []
    for image, label, prob, correct in zip(all_images, all_labels, all_probs, corrects):
        if not correct:
            incorrect_examples.append((image, label, prob))

    incorrect_examples.sort(reverse=True, key=lambda x: torch.max(x[2]).item())
    N_IMAGES = 6
    plot_most_incorrect(incorrect_examples, class_names, N_IMAGES)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

run_training(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    test_loader=test_loader,
    optimizer=optimizer,
    criterion=criterion,
    device=device,
    class_names=['class1','class2','class3','class4'],
    num_epochs=100,
    patience=40
)